KeyviDev/keyvi

keyvi/include/keyvi/dictionary/dictionary_compiler.h
keyvi/include/keyvi/dictionary/dictionary_merger.h
keyvi/include/keyvi/dictionary/fsa/automata.h
keyvi/include/keyvi/dictionary/fsa/generator.h
keyvi/include/keyvi/dictionary/fsa/internal/json_value_store.h
keyvi/include/keyvi/dictionary/fsa/internal/sparse_array_persistence.h
keyvi/include/keyvi/dictionary/fsa/internal/string_value_store.h
keyvi/include/keyvi/dictionary/keyvi_file.h
keyvi/include/keyvi/index/index.h
keyvi/include/keyvi/index/internal/base_index_reader.h
keyvi/include/keyvi/index/internal/index_reader_worker.h
keyvi/include/keyvi/index/internal/index_writer_worker.h
keyvi/include/keyvi/index/internal/merge_job.h
keyvi/include/keyvi/index/internal/merge_policy.h
keyvi/include/keyvi/index/internal/read_only_segment.h
keyvi/include/keyvi/index/internal/segment.h
keyvi/include/keyvi/index/internal/simple_merge_policy.h
keyvi/include/keyvi/testing/index_mock.h
keyvi/include/keyvi/testing/temp_dictionary.h
keyvi/include/keyvi/util/serialization_utils.h
keyvi/tests/keyvi/dictionary/dictionary_compiler_test.cpp
keyvi/tests/keyvi/dictionary/dictionary_merger_test.cpp
keyvi/tests/keyvi/index/index_test.cpp
keyvi/tests/keyvi/index/internal/merge_policy_selector_test.cpp
keyvi/tests/keyvi/index/internal/read_only_segment_test.cpp
keyvi/tests/keyvi/index/internal/segment_test.cpp
keyvi/tests/keyvi/index/read_only_index_test.cpp
python/src/addons/Index.pyx
python/src/pxds/index.pxd

[index] Index deletes

---

keyvi/include/keyvi/dictionary/fsa/internal/serialization_utils.h

- boost json parser depends on boost::spirit, and spirit is not thread-safe by default. so need to enable thread-safety
(cherry picked from commit 96ca66c632e96fe2206ea9409b774e5c89f2aacc)

thread-safe boost::spirit

---

keyvi/include/keyvi/util/vint.h
keyvi/tests/keyvi/util/vint_test.cpp

fixes a off by 1 miscalculation between the length calculated by getVarshortLength and encodeVarshort, while the 1st returned 2 for 0x7fff the 2nd correctly returned 1 as 0x7fff fits in 1 byte (0111 1111 1111 1111 ).  The same bug existed for the next boundary 0x3fffffff. 
As a result of this miscalculation it was possible - although rather unlikely - that a bit in a bitvector was set, marking a written cell while it did not got written as the required space was 1 instead of 2. The consequence of the unwritten cell is a default to '\0', this '\0' caused a  mismatch starting with version 0.2 where '\0' became a valid transition. This broken transition caused a segfault  due to a broken pointer.

fix a bug in variable length short calculation which can cause corrupt keyvi files

---

keyvi/include/keyvi/dictionary/dictionary_merger.h
keyvi/include/keyvi/index/index.h
keyvi/include/keyvi/index/internal/constants.h
keyvi/include/keyvi/index/internal/index_settings.h
keyvi/include/keyvi/index/internal/index_writer_worker.h
keyvi/include/keyvi/index/internal/merge_job.h
keyvi/tests/keyvi/dictionary/dictionary_merger_test.cpp
keyvi/tests/keyvi/index/index_test.cpp
keyvi/tests/keyvi/index/internal/index_settings_test.cpp
keyvi/tests/keyvi/index/internal/merge_job_test.cpp
keyvi/tests/keyvi/unit_tests_all.cpp
python/setup.py
travis/build_linux.sh
travis/build_osx_package.sh

with this PR the python package is fully self-contained again. keyvimerger already shipped with the package but the code in the C++ part was missing.

[index] finish keyvimerger integration as part of the python package

---

.travis.yml

Building coverage only when destination is the upstream branch, so forks travis builds will not fail while trying to post something to coveralls.io.
see: https://travis-ci.org/narekgharibyan/keyvi-1/jobs/342801767

Travis - coverage

---

keyvi/include/keyvi/dictionary/fsa/internal/lru_generation_cache.h
keyvi/include/keyvi/dictionary/fsa/internal/minimization_hash.h
keyvi/tests/keyvi/dictionary/fsa/internal/minimization_hash_test.cpp

fix a couple of namings and types in minimization hash as well as memory usage calculation

fix a couple of type issues in minimization hash

---

CMakeLists.txt
python/setup.py

rewrite cmake target to introduce `make bindings` instead of using a build type

[index] rewrite make bindings

---

.travis.yml
travis/build_manylinux_wheels.sh
travis/setup_pyenv.sh

- added CPython 3.6 builds to travis
- build docs only for master on upstream repo

CPython 3.6 builds

---

CMakeLists.txt
keyvi/include/keyvi/dictionary/fsa/automata.h
keyvi/include/keyvi/dictionary/util/endian.h
keyvi/include/keyvi/vector/types.h
keyvi/include/keyvi/vector/vector.h
keyvi/include/keyvi/vector/vector_file.h
keyvi/include/keyvi/vector/vector_generator.h
keyvi/include/keyvi/vector/vector_types.h
keyvi/tests/keyvi/vector/basic_test.cpp
python/.gitignore
python/setup.py
python/src/addons/JsonVector.pyx
python/src/addons/JsonVectorGenerator.pyx
python/src/pxds/vector.pxd
python/src/pxds/vector_generator.pxd
python/src/py/keyvi/vector/__init__.py
python/tests/vector/basic_test.py

This implements `keyvi.vector` which is a `vector` like `read-only` data-structure implemented by utilizing `mmap`. It enables possibility to access data via just 2 page accesses and basically has a 0 memory requirement.
Some stuff that can be added later: 
- `msgpack` can be used from python bindings to make it even faster
- `resize()` like functionality in order to enable assignment by index, and not just only `PushBack`
- `cross-architecture` support - `done`

keyvi vector

---

keyvi/include/keyvi/dictionary/fsa/internal/memory_map_manager.h

adds error handling to memory map manager so that problems like exhausted file handles get visible.
relates #60

add error handling in memorymapmanager

---

keyvi/include/keyvi/index/internal/index_writer_worker.h
keyvi/include/keyvi/index/internal/merge_job.h
keyvi/include/keyvi/index/internal/merge_policy.h
keyvi/include/keyvi/index/internal/read_only_segment.h
keyvi/include/keyvi/index/internal/segment.h
keyvi/include/keyvi/index/internal/simple_merge_policy.h
keyvi/tests/keyvi/index/index_test.cpp
keyvi/tests/keyvi/index/internal/segment_test.cpp

Fix an issue that deleted keys were not loaded correctly on index reload from disk. Also fixes lazy loading for segments in writer.

Fix issue with deleted keys on index reload and lazy loading

---

python/setup.py

adds python 3.6 to description
Should fix the badge after the next release

add python 3.6 as classifier

---

keyvi/include/keyvi/index/constants.h
keyvi/include/keyvi/index/internal/index_auto_config.h
keyvi/include/keyvi/index/internal/index_settings.h
keyvi/include/keyvi/index/internal/index_writer_worker.h
keyvi/include/keyvi/util/active_object.h
keyvi/include/keyvi/util/os_utils.h
keyvi/include/keyvi/util/single_producer_consumer_ringbuffer.h
keyvi/tests/keyvi/index/index_limits_test.cpp
keyvi/tests/keyvi/index/index_test.cpp
keyvi/tests/keyvi/util/single_producer_consumer_ringbuffer_test.cpp

This change implements auto-configuration of index settings, including configuring the maximum number of segments which is directly connected to the number of file descriptors. If not externally given it tries to increase the limit (usually from 1024 to 1M). In case of running low on file descriptors index operations are automatically throttled so that concurrent compaction can catch up and reduce open descriptors.
Also changes the queue implementation - after benchmarking - to use condition variables instead of a spin-lock if the queue runs full or empty. This improves indexing performance and also fixes a problem in the spin-lock implementation that could cause cpu hogging. 
fixes #60

Index Autoconfiguration, overcoming filedescriptor limitations

---

python/requirements.txt
python/setup.py

Set minimum version for msgpack, as we depend on API introduced in 0.5.2. (`raw flag in msgpack.loads(packed_value, raw=False)`) and also some bug fixes were added later on.

Minimum version for msgpack

---

keyvi/include/keyvi/dictionary/fsa/internal/bit_vector.h
keyvi/include/keyvi/dictionary/fsa/internal/bit_vector_64.h

cleanup naming, use C++ limits instead of limits.h. Fix a potential out of bounds access.
Note: The out of bounds problem does not happen in production, at least not until now except for the unit test. In prod the 1st bit vector is always larger than the to second one, nevertheless good to fix it.

cleanup code style, fix a potential out of bounds bug

---

keyvi/include/keyvi/dictionary/fsa/internal/sparse_array_builder.h
keyvi/include/keyvi/dictionary/fsa/internal/sparse_array_persistence.h
keyvi/include/keyvi/dictionary/util/endian.h
keyvi/tests/keyvi/dictionary/fsa/internal/sparse_array_builder_test.cpp

fix some  types, constants and namings

some small cleanups and type fixes

---

keyvi/include/keyvi/dictionary/fsa/internal/memory_map_manager.h
keyvi/include/keyvi/dictionary/fsa/internal/sparse_array_persistence.h
keyvi/tests/keyvi/dictionary/fsa/internal/sparse_array_builder_test.cpp

fix a bug in reading transition values during construction which can be spread across 2 chunks.
This issue found in the code has probably not much impact in practice, nevertheless worth to fix. If a transition value is stored between 2 chunks (1st part in chunk x, 2nd part in chunk x+1) the value wasn't read correctly. Note that chunking is only done at construction time, so lookup isn't affected. Reading the transition value is part of minimization, so worst case this bug prevented minimization of this particular state. I can not think this issue can cause data corruption.

fix a corner case, reading a transition value which is spread across 2 chunks

---

.travis.yml

This enables an opportunity for forks to submit their coverage results to coveralls, and see coverage  without opening a pull request.
Example: https://coveralls.io/github/narekgharibyan/keyvi-1

Enabled coveralls for forks

---

keyvi/bin/keyvicompiler/keyvicompiler.cpp
keyvi/include/keyvi/dictionary/dictionary_compiler.h
keyvi/include/keyvi/dictionary/dictionary_merger.h
keyvi/include/keyvi/dictionary/fsa/generator.h
keyvi/include/keyvi/dictionary/fsa/generator_adapter.h
keyvi/tests/keyvi/dictionary/fsa/generator_test.cpp
python/src/addons/CompletionDictionaryCompiler.pyx
python/src/addons/CompletionDictionaryMerger.pyx
python/src/addons/IntDictionaryCompiler.pyx
python/src/addons/IntDictionaryMerger.pyx
python/src/addons/JsonDictionaryCompiler.pyx
python/src/addons/JsonDictionaryCompilerSmallData.pyx
python/src/addons/JsonDictionaryMerger.pyx
python/src/addons/KeyOnlyDictionaryCompiler.pyx
python/src/addons/KeyOnlyDictionaryMerger.pyx
python/src/addons/StringDictionaryCompiler.pyx
python/src/addons/StringDictionaryMerger.pyx
python/src/pxds/dictionary_compiler.pxd
python/src/pxds/dictionary_merger.pxd

removes SetManifest(boost:ptree) in favor of SetManifest(std::string), the first wasn't in use, so it is IMHO safe to remove.
relates #80

remove SetManifest from boost property trees

---

keyvi/CPPLINT.cfg
keyvi/include/keyvi/dictionary/dictionary_merger.h
keyvi/include/keyvi/dictionary/dictionary_properties.h
keyvi/include/keyvi/dictionary/fsa/automata.h
keyvi/include/keyvi/index/constants.h
keyvi/include/keyvi/index/internal/merge_policy_selector.h
keyvi/include/keyvi/index/internal/read_only_segment.h
keyvi/include/keyvi/index/internal/segment.h
keyvi/include/keyvi/index/internal/simple_merge_policy.h
keyvi/include/keyvi/index/internal/tiered_merge_policy.h
keyvi/tests/keyvi/index/index_test.cpp
keyvi/tests/keyvi/index/internal/tiered_merge_policy_test.cpp

The tiered merge policy is a smarter selection algorithm for selecting segments to merge. It scores sets of segments while prefering similar sized segments while boosting smaller merges and segments with deletes.
The algorithm is inspired by Lucene's tiered merge policy.
This change makes the tiered merge policy the default

add a tiered merge policy

---

keyvi/tests/keyvi/index/index_limits_test.cpp

for a unit test the file descriptor limit was set to just 20. This caused another test to fail. The fix resets the number of file descriptor to the limit before the test.

reset old filedescriptor limit after test

---

keyvi/include/keyvi/index/constants.h
keyvi/include/keyvi/index/internal/index_settings.h
keyvi/include/keyvi/index/internal/index_writer_worker.h
keyvi/include/keyvi/index/internal/merge_job.h
keyvi/tests/keyvi/index/index_test.cpp
travis/build_linux.sh
travis/build_osx_package.sh

implements internal merges without using an external process, merges of smaller segments are done in-process decided by a static threshold. The threshold decides when to switch to external process based merging.

implement internal merges without an external process

---

.travis.yml
docker/ubuntu-builder/Dockerfile

drop python 3.4.9 and add 3.8.0
Note:
- we should also modernize other parts, e.g. bump XCode, manylinux, linux compilers?, all to be done in follow-ups

drop python 3.4.9 and add 3.8.0

---

keyvi/include/keyvi/dictionary/dictionary_properties.h
keyvi/include/keyvi/index/index.h
keyvi/include/keyvi/index/internal/base_index_reader.h
keyvi/include/keyvi/index/internal/index_reader_worker.h
keyvi/include/keyvi/index/internal/index_writer_worker.h
keyvi/include/keyvi/index/internal/segment.h
keyvi/include/keyvi/vector/vector_file.h
keyvi/tests/keyvi/index/index_test.cpp

- fix segment vector caching: due to lazy loading of the dictionary file, the file might have been deleted already at the time of a lookup (issue seen on CI)
- fix segment invalidation: the cache never got invalidated in case of a constant stream of lookups (the reference count of the cache never reached 0), invalidation is now enforced for every new segment and after a merge
- implement force merge: the force merge command blocks until segments are merged down to the given number of segments
Notes:
- force merge was implemented for testing the invalidation/caching problem, there is no "force" right now, but it blocks until merges are done automatically, however in future force merge could do a real "force"
- it's also called "force merge" in lucene: common wording

Fix Segment invalidation issue

---

keyvi/include/keyvi/index/index.h
keyvi/include/keyvi/index/internal/index_writer_worker.h
keyvi/tests/keyvi/index/index_test.cpp
python/src/pxds/index.pxd

make mset parameter flexible, merge flush and flush async
Note:
the mset change is motivated by protobuf, it allows to use protobuf's map implementation directly

improve mset

---

.travis.yml
docker/manylinux-builder/Dockerfile
python/setup.py

- updated manylinux base image to `quay.io/pypa/manylinux2014_x86_64`, more info here: https://www.python.org/dev/peps/pep-0599/
- dropped python 2.7 support

update manylinux docker image base 

---

python/tests/dictionary_compiler_test.py

call gc, so that the compiler should be gone on pypy

fix test hickup for pypy

---

keyvi/include/keyvi/index/internal/segment.h

make lazy loading thread-safe
fixes #153

Fix race condition in index when concurrently accessing same segment

---

doc/usage/Building keyvi dictionaries with python.md
doc/usage/Building keyvi dictionaries.md
doc/usage/Crashcourse.md
python/examples/completion/multiword_completion_tester.py
python/examples/completion/multiword_completion_writer.py
python/examples/completion/prefix_completion_fuzzy_tester.py
python/examples/completion/prefix_completion_tester.py
python/examples/lookup/text_lookup_tester.py
python/examples/lookup/value_lookup_tester.py
python/examples/normalization/normalize.py

rewrite examples python 3, use .kv instead of .keyvi as file suffix

update examples to python 3

---

docker/ubuntu-builder/Dockerfile

This should fix failing Rust builds, the error [here](https://travis-ci.com/github/KeyviDev/keyvi/jobs/419682200) says: 
```
thread 'main' panicked at '`libclang` function not loaded: `clang_Cursor_isFunctionInlined`. This crate requires that `libclang` 3.9 or later be installed on your system.
```
Clang coming with `apt` on `ubuntu 16.04` has version `3.8`. On `ubuntu 20.04` version is `10`
```
root@47e6ed3ca889:/# clang --version
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Bump ubuntu version

---

.travis.yml

Image with new `ubuntu:20.04` doesn't produce consistent coverage report. we need to investigate that separately, but no need to block current PRs. so we can use `ubuntu:16.04` base image temporarily.

Use ubuntu 16.04 for coverage build

---

.github/workflows/python.yml

use github actions for CI, implements builders on linux and macOS for the python build

 use github actions for CI - python

---

.github/workflows/keyvi.yml
.github/workflows/python.yml
.github/workflows/style.yml

Tested this on my fork, it enables builds on all branches. Which is especially handy for development.

enable builds for all branches

---

.github/workflows/keyvi.yml

cmakeBuildType is only used in basic mode, advanced mode requires cmakeAppendedArgs

correct cmake build type 

---

python/setup.py

rewrite autowrap output to use std::shared_ptr instead of boost::shared_ptr, fixes compiler aliasing warnings
relates https://github.com/uweschmitt/autowrap/pull/83

remove boost::shared_ptr from generated python bindings

---

.github/workflows/style.yml
keyvi/check-style.sh

The style checks was still using a travis env variables which returned an empty set of files, making the check no do anything. This change uses gh action variables instead.

fix gh style check action

---

keyvi/include/keyvi/dictionary/fsa/internal/lru_generation_cache.h
keyvi/include/keyvi/dictionary/fsa/internal/minimization_hash.h
keyvi/tests/keyvi/dictionary/fsa/internal/json_value_store_test.cpp
keyvi/tests/keyvi/dictionary/fsa/internal/minimization_hash_test.cpp

For memory limits > 99272 MB a bug in memory calculation triggered, resulting in super slow execution and loss of minimization. This change fixes the bug, ensuring the maximum possible configuration is returned and not configuration with `0`. It also allows creating an even bigger hashtable by adding another prime. LBNL the minimum memory limit is checked and an exception is thrown.
fixes #205

Fix memory limit calculation for memory limits > 99272 MB

---

keyvi/include/keyvi/dictionary/dictionary.h
keyvi/include/keyvi/dictionary/fsa/codepoint_state_traverser.h
keyvi/include/keyvi/dictionary/fsa/comparable_state_traverser.h
keyvi/include/keyvi/dictionary/fsa/state_traverser.h
keyvi/include/keyvi/dictionary/fsa/zip_state_traverser.h
keyvi/include/keyvi/dictionary/matching/fuzzy_matching.h
keyvi/include/keyvi/stringdistance/needleman_wunsch.h
keyvi/tests/keyvi/dictionary/fsa/comparable_state_traverser_test.cpp
keyvi/tests/keyvi/dictionary/fsa/zip_state_traverser_test.cpp
keyvi/tests/keyvi/dictionary/matching/fuzzy_matching_test.cpp

The current traverser objects only allow to traverse single dictionaries. However indexes consist of several segments==dictionaries. The ZipStateTraverser wraps a collection of traversers(e.g. a traverser per segment) providing a single traverser. Longer term this will allow fuzzy and completion matching on an index.

add ZipStateTraverser

---

CMakeLists.txt
keyvi/include/keyvi/index/constants.h
keyvi/include/keyvi/util/msgpack_util.h
keyvi/tests/keyvi/compression/fsa_predictive_compression_test.cpp
keyvi/tests/keyvi/index/index_limits_test.cpp
keyvi/tests/keyvi/index/index_test.cpp
keyvi/tests/keyvi/unit_tests_all.cpp

fix setenv on windows, msgpack util and keyvimerger binary name
With these final fixes I am able to compile and run the unit tests on windows except `fsa_predictive_compression_test` which is a feature that is rather experimental (I consider removing it completely).

fix remaining windows issues

---

keyvi/include/keyvi/dictionary/dictionary_index_compiler.h
keyvi/tests/keyvi/dictionary/dictionary_index_compiler_test.cpp

switches the parallel sorting algorithm. This fixes the segfault reported in #215.
relates #215
I think it makes sense to apply this change until a better solution has been found.

switch the parallel sorting algorithm

---

keyvi/include/keyvi/dictionary/fsa/comparable_state_traverser.h
keyvi/include/keyvi/dictionary/fsa/state_traverser.h
keyvi/include/keyvi/dictionary/fsa/traversal/traversal_base.h
keyvi/include/keyvi/dictionary/fsa/zip_state_traverser.h
keyvi/tests/keyvi/dictionary/fsa/comparable_state_traverser_test.cpp
keyvi/tests/keyvi/dictionary/fsa/zip_state_traverser_test.cpp
keyvi/tests/keyvi/dictionary/matching/fuzzy_matching_test.cpp

This change add support for weighted state traversal in comparable/zip state traverser. This is the 1st step in order to support completions with inner weights from keyvi indexes.
When combining the traversers, inner weights have to be normalized, that means a global weight map has to be created and transitions need to be sorted the same way for all inner traversers. This can be expensive, however as segments get merged quite quickly, this is probably only a problem for the 1st levels in the tree.

ZipStateTraverser: support state traversal with inner weights

---

keyvi/include/keyvi/dictionary/completion/prefix_completion.h
keyvi/tests/keyvi/dictionary/completion/prefix_completion_test.cpp
python/src/pxds/prefix_completion.pxd
python/tests/completion/fuzzy_completion_test.py

check utf8 length when matching exact prefix for fuzzy completion and make the exact prefix configurable
fixes #234

Fix exact prefix matching for fuzzy completion for utf8 charactors

---

keyvi/include/keyvi/dictionary/fsa/traversal/near_traversal.h
keyvi/tests/keyvi/dictionary/fsa/traversal/near_traversal_test.cpp
keyvi/tests/keyvi/dictionary/fsa/zip_state_traverser_test.cpp

near traversal did not follow the exact path for non-ascii characters due to a type mismatch when comparing: unsigned char vs char

Fix near traversal for non ascii characters

---

rust/src/dictionary.rs

`char` type is not specifically defined. It can be signed or unsigned depends
on architecture.
On x86 `char` is signed but on some ARM platforms char can be signed or unsigned.
```
int main() {
char c = -1;
if (c > 0)
printf("c is positive \n");  // Docker container on Apple M1
else
printf("c is negative \n");  // Native Apple M1
}
```
The output will be "c is negative" on Apple M1 and "c is positibe" on linux
docker container on Apple M1.
Let's use `c_char` which is portable.
More details:
https://developer.arm.com/documentation/den0013/d/Porting/Miscellaneous-C-porting-issues/unsigned-char-and-signed-char
https://doc.rust-lang.org/std/os/raw/type.c_char.html

portable c-char in dictionary.rs

---

keyvi/include/keyvi/util/os_utils.h
python/setup.py

This PR adds missing:
- `#include` statement 
- link library dir for python 3.10
to make CI green again.

Added missing include and link dir to make CI green again 

---

rust/src/dictionary.rs

There is one more pointer to fix. I overlooked it in my previous pull request:
https://github.com/KeyviDev/keyvi/pull/250
PS. May you release a new version with all latest changes?

(one more) portable c-char in dictionary.rs

---

.github/workflows/manylinux.yml

* Use the `aarch64` and `x86_64` images from #254 to actually build `linux/aarch64` and `linux/x86_64` wheels of `keyvi`
* Docker uses [QEMU](https://www.qemu.org) to run containers with images of different architecture, so there's a `docker/setup-qemu-action@v2`
* The docker images used in the build are now specified in the matrix. That's why there's no `container` entry in the job anymore and we need to actually bring the `addnab/docker-run-action@v3` in order to run different images from the matrix in the job

Build keyvi for arm as well

---

python/build_macosx_wheels.sh

Apparently some build artifacts are not compatible between Python version, like Cython generated code. 
This PR removes build artifacts between different versions, so all wheels are build in one script execution.

Fix - remove build artifacts between mac os builds

---

keyvi/bin/keyvicompiler/keyvicompiler.cpp

fix a bug in keyvicompiler, instead of completion dictionary it created an integer dictionary

fix compilation of completion dictionaries with keyvicompiler 

---

docker/manylinux-builder/Dockerfile
docker/manylinux-builder/build_and_push.sh

update docker files, more use of parallel building, add ccache and support of musllinux
~Note: There seems to be a problem with the manylinux on arm image. For some reason snappy isn't found although it gets installed.~
FWIW There was a problem with the boost download(server unavailable), I added support for a fallback.

Update docker images, add musllinux build image and ccache support

---

keyvi/include/keyvi/dictionary/fsa/state_traverser.h

fixes a small issue in state traverser, there was a public GetTraversalPayload, but that is is not intended. It used by a near traversal which has access via friend. So most likely this is some development leftover (removing the method does not work, it is needed).

Fix small access issue for near traversal

---

CMakeLists.txt
README.md
keyvi/.clang-format
keyvi/include/keyvi/dictionary/matching/near_matching.h
keyvi/tests/keyvi/vector/basic_test.cpp

switches to C++17 to be able to use make_unique and other features from C++14 and beyond.
According to cibuildwheel [docs](https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/) C++17 should be possible with the builders we are using, C++20 however is not supported yet.

switch to C++17

---

keyvi/include/keyvi/dictionary/dictionary.h
keyvi/include/keyvi/dictionary/fsa/codepoint_state_traverser.h
keyvi/include/keyvi/dictionary/matching/fuzzy_multiword_completion_matching.h
keyvi/include/keyvi/stringdistance/needleman_wunsch.h
keyvi/tests/keyvi/dictionary/completion/prefix_completion_test.cpp
python/src/pxds/dictionary.pxd
python/tests/completion/fuzzy_completion_test.py
python/tests/dictionary/dictionary_fuzzy_multiword_completion_test.py

implement a fuzzy version of multiword completion matching. This change also fixes a couple of fuzzy completion matching issues and simplifies the distance matrix calculations.
Note:
- the distance calculation for cases where fuzzy completions are combined with a character deletion, e.g. completing "finnite state"(note the double "n") to "finite state traverser", was totally broken
- there was also a case where completions required the last character to be an exact match, not sure where this came from, but this can be handled by the caller

Implement multiword completions with fuzzy matching support

---

python/src/addons/match_iterator.pyx

this change releases the GIL during matching in match iterator. Especially for fuzzy matching the GIL is unnecessarily locked for quite some time, causing python apps to not being able to react.

python: release the GIL during matching in match iterator

---

.github/workflows/keyvi.yml
CMakeLists.txt
keyvi/.clang-tidy
keyvi/tests/.clang-tidy

add some basic clang-tidy checks

add clang-tidy checks

---

.github/workflows/python-cibuildwheel.yml
python/pyproject.toml
python/requirements.txt
python/setup.py

Fixes builds using the latest cibuildwheel. Due to incompatible changes introduced upstream pypy(https://github.com/pypa/distutils/issues/283) had to be taken out for now.
In the long run we should switch away from setuptools, so these changes are just considered temporary until #310 is ready.

Adapt build to new cibuildwheel and other upstream changes

---

.github/workflows/rust.yml
rust/Cargo.toml

up bindings to `>= 0.69.5` to prevent creating empty bindings on ubuntu 24.04. In addition add a workflow that checks compatibility for the news versions of rust dependencies

fix build issue for rust binding on ubuntu 24.04

---

keyvi/CPPLINT.cfg
keyvi/include/keyvi/dictionary/dictionary_compiler.h
keyvi/include/keyvi/dictionary/dictionary_index_compiler.h
keyvi/tests/.clang-tidy
keyvi/tests/keyvi/dictionary/dictionary_compiler_test.cpp

prevent a double free crash if Compile gets called more than once

bug: fix crash if Compile gets called twice

---

keyvi/3rdparty/utfcpp/.gitmodules

remove `.gitmodule` from utfcpp 3rdparty dependency. This allows building keyvi from git in a rust project.

remove git submodule from utfcpp dependency

---

keyvi/bin/keyvi_c/c_api.cpp
keyvi/bin/keyvicompiler/keyvicompiler.cpp
keyvi/bin/keyviinspector/keyviinspector.cpp
keyvi/bin/keyvimerger/keyvimerger.cpp

apply clang tidy fixes using `--fix-errors`, fixes most of the errors in `keyvi/bin`.

apply clang tidy fixes to binaries

---

.github/workflows/python-cibuildwheel.yml
python/setup.py

github made arm runners freely available, finally we can drop QEMU and cross-compiled builds

drop QEMU builds and use native arm runners for Linux and Mac

---

.github/workflows/docs.yml
.github/workflows/keyvi.yml
keyvi/include/keyvi/dictionary/match.h
keyvi/include/keyvi/index/internal/index_writer_worker.h
keyvi/include/keyvi/index/internal/merge_job.h
keyvi/tests/keyvi/index/index_limits_test.cpp
keyvi/tests/keyvi/index/internal/merge_job_test.cpp
python/src/addons/JsonVector.pyx

Migrate to boost process v2, fixes compile problems on newer versions of boost.
In addition:
- fix autowrap API breakage
- fix doc build
- fix concurrency issue in keyvi index which appeared after boost process update on Mac

Migrate to boost process v2

---

.github/workflows/python-dockerimages-cibuildwheel.yml

musllinux_1_1 is EOL since 11/2024, cibuildwheel dropped support. Therefore upgrading to 1_2

update musl base image to 1_2

---

.github/workflows/keyvi.yml
.github/workflows/python-cibuildwheel.yml
python/pyproject.toml
python/requirements.txt

switch to trusted publishing, skip unnecessary double build on mac, cleanup and bump versions

Switch to pypi trusted workflow publishing, cleanup build workflows

---

.github/workflows/python-cibuildwheel.yml

switch macos-13 to macos-15-intel, see:
see https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/

switch to macos-15-intel

---

keyvi/include/keyvi/dictionary/dictionary.h
keyvi/include/keyvi/dictionary/fsa/comparable_state_traverser.h
keyvi/include/keyvi/dictionary/fsa/state_traverser.h
keyvi/tests/keyvi/dictionary/fsa/comparable_state_traverser_test.cpp
keyvi/tests/keyvi/dictionary/fsa/state_traverser_test.cpp

removes an unnecessary bool in state traverser and fixes clang-tidy warnings in corresponding tests

cleanup state traverser from unnecessary member

---

python/integration-tests/compiler/var_length_short_calculation_test.py
python/integration-tests/dictionary/dictionary_leak_test.py
python/tests/dictionary/loading_test.py
python/tests/index/merger_binary_test.py

test fixes from scikit-buildcore branch

fix some deprecations and other python warnings in tests
