- .travis.yml
- keyvi/.clang-format
- keyvi/CPPLINT.cfg
- keyvi/check-style.sh
- keyvi/include/keyvi/dictionary/dictionary.h
- keyvi/include/keyvi/dictionary/dictionary_compiler.h
- travis/setup_pyenv.sh
- travis/style.sh
Add style checking, starting with cpplint and clang-format and a 1st configuration. Checking is done incrementally: Only changed files are verified.
> Add a stylechecker for C++ files

- add-remotes.sh
- keyvi/3rdparty/pull-tiny-process-lib.sh
- keyvi/3rdparty/tiny-process-library/.gitignore
- keyvi/3rdparty/tiny-process-library/.travis.yml
- keyvi/3rdparty/tiny-process-library/CMakeLists.txt
- keyvi/3rdparty/tiny-process-library/LICENSE
- keyvi/3rdparty/tiny-process-library/README.md
- keyvi/3rdparty/tiny-process-library/examples.cpp
- keyvi/3rdparty/tiny-process-library/process.cpp
- keyvi/3rdparty/tiny-process-library/process.hpp
- keyvi/3rdparty/tiny-process-library/process_unix.cpp
- keyvi/3rdparty/tiny-process-library/process_win.cpp
- keyvi/3rdparty/tiny-process-library/tests/CMakeLists.txt
- keyvi/3rdparty/tiny-process-library/tests/io_test.cpp
- keyvi/3rdparty/tiny-process-library/tests/multithread_test.cpp
- keyvi/3rdparty/tiny-process-library/tests/open_close_test.cpp
add tiny process library as 3rd party module in preparation for indexer library
> Add tiny process

- keyvi/bin/keyvimerger/keyvimerger.cpp
- keyvi/include/keyvi/dictionary/dictionary_compiler.h
- keyvi/include/keyvi/dictionary/dictionary_merger.h
- keyvi/include/keyvi/dictionary/sort/in_memory_sorter.h
- keyvi/include/keyvi/dictionary/sort/tpie_sorter.h
- python/src/pxds/dictionary_compiler.pxd
- python/src/pxds/dictionary_merger.pxd
remove/cleanup the old memory_limit interfaces
> remove deprecated interfaces

- keyvi/bin/keyvicompiler/keyvicompiler.cpp
- keyvi/bin/keyviinspector/keyviinspector.cpp
- keyvi/bin/keyvimerger/keyvimerger.cpp
cleans up binaries and adds parameters to merger, consistent to the compiler
> cleanup binaries

- .travis.yml
- docker/manylinux/Dockerfile
> Update docker image

- python/setup.py
@hendrikmuhs can you please to make a release, as you know better about changes since v0.2.5 release ?
> Version bump for 0.2.6 release

- keyvi/include/keyvi/index/index.h
- keyvi/include/keyvi/index/internal/index_writer_worker.h
- keyvi/tests/keyvi/index/index_test.cpp
- python/src/addons/Index.pyx
- python/src/pxds/index.pxd
- python/tests/index/index_test.py
splits Flush(bool async) into Flush and FlushAsync  for the purpose of being more explicit
> [index] split Flush api into Flush and FlushAsync

- keyvi/include/keyvi/index/constants.h
- keyvi/include/keyvi/index/index.h
- keyvi/include/keyvi/index/internal/base_index_reader.h
- keyvi/include/keyvi/index/internal/index_reader_worker.h
- keyvi/include/keyvi/index/internal/index_settings.h
- keyvi/include/keyvi/index/internal/index_writer_worker.h
- keyvi/include/keyvi/index/read_only_index.h
- keyvi/tests/keyvi/index/index_test.cpp
- keyvi/tests/keyvi/index/internal/merge_job_test.cpp
move constants file 1 directory up
> [index] Index move constants

- keyvi/CPPLINT.cfg
- keyvi/include/keyvi/dictionary/completion/multiword_completion.h
- keyvi/include/keyvi/dictionary/completion/prefix_completion.h
- keyvi/include/keyvi/stringdistance/distance_matrix.h
This PR include small type fixes from https://github.com/cliqz-oss/keyvi/pull/242
As `style-check` requires whole file to be formatted properly decided to have a separate PR for this, to make review easier.
> Minor type fixes and formatting

- keyvi/include/keyvi/dictionary/dictionary_compiler.h
- keyvi/include/keyvi/dictionary/dictionary_merger.h
- keyvi/include/keyvi/dictionary/fsa/generator.h
- keyvi/tests/keyvi/dictionary/dictionary_merger_test.cpp
this change instruments dictionary merger to retrieve stats about number of deleted/overwritten keys
> [index] instrument merger with stats and make interface more like compiler

- keyvi/include/keyvi/dictionary/dictionary_merger.h
- keyvi/include/keyvi/index/internal/base_index_reader.h
- keyvi/include/keyvi/index/internal/index_settings.h
- keyvi/include/keyvi/index/internal/index_writer_worker.h
- keyvi/include/keyvi/index/internal/merge_policy_selector.h
- keyvi/include/keyvi/util/single_producer_consumer_ringbuffer.h
- keyvi/tests/keyvi/index/internal/merge_policy_selector_test.cpp
- keyvi/tests/keyvi/util/single_producer_consumer_ringbuffer_test.cpp
- python/.gitignore
addresses review comments from #37
> [index] adress review comments

- keyvi/include/keyvi/index/internal/segment.h
- python/setup.py
- python/src/addons/Index.pyx
- python/tests/index/merger_binary_test.py
address remaining issues of #37
> [index] Index fix review comments2

- keyvi/include/keyvi/dictionary/fsa/generator.h
- keyvi/include/keyvi/dictionary/fsa/internal/constants.h
removes dead code from generator
> remove dead code from generator

- rust/Cargo.toml
- travis/setup_rust.sh
This fixes rust builds on travis and adds mandatory changes for publishing on https://crates.io
> Rust package

- .gitignore
- keyvi/include/keyvi/dictionary/fsa/internal/constants.h
- keyvi/include/keyvi/dictionary/fsa/internal/sliding_window_bit_vector_position_tracker.h
This commit replaces defines with const variables
Also, adds vim swap files in .gitignore
> Replaced defines with const variables.

- keyvi/include/keyvi/dictionary/fsa/internal/constants.h
> add missing header

- keyvi/include/keyvi/index/internal/segment.h
- keyvi/include/keyvi/testing/index_mock.h
fully write deleted keys for index mock then swap
fixes #81
> fully write deleted keys for index mock then swap

- python/.gitignore
- python/setup.py
- python/src/py/keyvi/__init__.py
- python/src/py/keyvi/cli/cli.py
- added --version option to keyvi cli
- moved version into keyvi/__init__.py file
- bumped version to 0.3.1dev
> Added --version option to keyvi cli

- keyvi/include/keyvi/dictionary/fsa/automata.h
- keyvi/include/keyvi/dictionary/fsa/generator.h
- keyvi/include/keyvi/dictionary/fsa/internal/sparse_array_persistence.h
- keyvi/include/keyvi/dictionary/util/endian.h
- keyvi/include/keyvi/util/serialization_utils.h
mainly fix endian handling in serialization utils, also some typo and style fixes
> Fix endian handling

- keyvi/include/keyvi/dictionary/fsa/automata.h
removes an unused variable, a leftover from persistence version 1 which has been removed in 0.2
> remove unused variable

- .travis.yml
switches build to the automatic docker images
> use images from the automatic docker builds

- keyvi/include/keyvi/compression/compression_selector.h
- keyvi/include/keyvi/dictionary/dictionary_compiler.h
- keyvi/include/keyvi/dictionary/dictionary_merger.h
- keyvi/include/keyvi/dictionary/fsa/generator.h
- keyvi/include/keyvi/dictionary/sort/tpie_sorter.h
- keyvi/include/keyvi/index/internal/merge_policy_selector.h
- keyvi/include/keyvi/vector/vector.h
removes deprecated dynamic exceptions and fixes compiler warnings
> Dynamic exceptions cleanup

- travis/build_sdist_package.sh
- travis/coverage.sh
- travis/style.sh
fix 3 places where 2.7.15 was still used
> use cpython 2.7.16

- keyvi/include/keyvi/dictionary/dictionary_compiler.h
- keyvi/include/keyvi/index/index.h
- keyvi/include/keyvi/index/internal/index_writer_worker.h
- keyvi/include/keyvi/index/types.h
- keyvi/tests/keyvi/index/index_test.cpp
- python/src/addons/Index.pyx
- python/src/addons/autwrap_workarounds.pyx
- python/src/pxds/index.pxd
- python/tests/index/index_test.py
add a bulk API to set a list of key/values at once
> add a bulk API for setting key/values (index)

- README.md
Release Process link in README.md throws 404 error. This PR updates the link to correct release process file.
> Fix release-process link

- docker/ubuntu-builder/Dockerfile
updates the docker configuration to install keyviserver requirements
> install protobuf and other required keyviserver deps

- .travis.yml
- keyvi/include/keyvi/dictionary/dictionary.h
- keyvi/tests/keyvi/dictionary/dictionary_test.cpp
- keyvi/tests/keyvi/transform/fsa_transform_test.cpp
- keyvi/tests/keyvi/util/active_object_test.cpp
- python/src/pxds/forward_backward_completion.pxd
- python/src/pxds/multi_word_completion.pxd
- python/src/pxds/normalization.pxd
- python/src/pxds/predictive_compression.pxd
- python/src/pxds/prefix_completion.pxd
- travis/build_osx_package.sh
- travis/setup_osx.sh
> OSX Travis upgrade xcode to 9.4

- .travis.yml
fixes #133 
CC @narekgharibyan: this got forgotten in #136 (sorry, I did not realize myself)
> Reenable rust in .travis.yml

- docker/ubuntu-builder/Dockerfile
build protocol buffer from source, for keyvi-server CI
> Protobuf docker

- .travis.yml
- python/integration-tests/compiler/var_length_short_calculation_test.py
- python/integration-tests/dictionary/dictionary_leak_test.py
- python/requirements.txt
- python/setup.py
- travis/build_osx_package.sh
- travis/build_python.sh
- travis/build_sdist_package.sh
- travis/coverage.sh
- travis/setup_osx.sh
drops remaining python 2.7 builds and reenables pypy builds
fixes #134
> drop python 2.7 support

- keyvi/include/keyvi/dictionary/completion/prefix_completion.h
- keyvi/include/keyvi/index/internal/base_index_reader.h
- keyvi/include/keyvi/stringdistance/costfunctions/damerau_levenshtein.h
- keyvi/include/keyvi/stringdistance/costfunctions/damerau_levenshtein_completion.h
- keyvi/include/keyvi/stringdistance/levenshtein.h
- keyvi/include/keyvi/stringdistance/needleman_wunsch.h
- keyvi/tests/keyvi/dictionary/completion/prefix_completion_test.cpp
- python/tests/completion/fuzzy_completion_test.py
overhaul fuzzy completion matching, introduce a separate completion mode in distance calculation and cost functions
fixes #50
> overhaul fuzzy completion matching

- python/requirements.txt
- python/setup.py
@hendrikmuhs I have tested on some files, before and after update I get exactly same results.
>  upgrade msgpack to 1.0.0

- travis/upload_packages.sh
remove set -e for package upload as it creates problem on OSX
> remove set -e for package upload

- travis/upload_packages.sh
switch to python -m for package upload
> fix upload_packages script for pypy

- keyvi/include/keyvi/stringdistance/needleman_wunsch.h
- keyvi/tests/keyvi/dictionary/matching/fuzzy_matching_test.cpp
fix overflow in distance calculation
fixes #155
> fix overflow in distance calculation

- keyvi/include/keyvi/dictionary/dictionary_compiler.h
- python/src/addons/CompletionDictionaryCompiler.pyx
- python/src/addons/IntDictionaryCompiler.pyx
- python/src/addons/IntDictionaryCompilerSmallData.pyx
- python/src/addons/JsonDictionaryCompiler.pyx
- python/src/addons/JsonDictionaryCompilerSmallData.pyx
- python/src/addons/KeyOnlyDictionaryCompiler.pyx
- python/src/addons/StringDictionaryCompiler.pyx
- python/src/pxds/dictionary_compiler.pxd
- python/tests/completion/multiword_completion_test.py
- python/tests/int/int_dictionary_test.py
move __setitem__ from cpp to the python binding
> move the __setitem__ method to the python binding

- .travis.yml
- docker/ubuntu-builder/Dockerfile
This PR adds new python versions on ubuntu builder.
I'll make a follow-up PR, which will drop old versions, after this PR is merged and dockerhub is updated.
On OS X we are installing python during travis run, so I made those updates in this PR.
> Add new python versions - part 1

- .github/workflows/style.yml
> workflow for style checking

- .github/workflows/keyvi.yml
use github actions for CI, implements builders on linux and macOS for core
> use github actions for CI - core

- .github/workflows/keyvi.yml
- .github/workflows/python.yml
- .github/workflows/style.yml
- docker/manylinux-builder/Dockerfile
update ubuntu base image to 20.04 to get a newer boost version, additionally update boost in manylinux docker image
relates #186
relates https://github.com/actions/virtual-environments/issues/1816
> update workflow image to ubuntu 20.04

- .github/workflows/manylinux.yml
- .travis.yml
- added `manylinux` GH action builds
- disabled `manylinux` builds on Travis-CI
> manylinux GH actions

- .github/workflows/keyvi.yml
- .github/workflows/python.yml
move ccache logic to gh action
> use ccache-action

- .github/workflows/manylinux.yml
- .github/workflows/python.yml
add gh workflow steps to upload a package after release
> gh action support for publishing a release on pypi

- keyvi/bin/keyvimerger/keyvimerger.cpp
- rust/tests/tests.rs
> fix compile problems on mac and rust

- keyvi/bin/keyvicompiler/keyvicompiler.cpp
- keyvi/include/keyvi/index/internal/index_writer_worker.h
- keyvi/include/keyvi/index/internal/merge_job.h
- keyvi/include/keyvi/index/internal/tiered_merge_policy.h
> fix warnings from clang

- CMakeLists.txt
- keyvi/include/keyvi/dictionary/dictionary.h
- keyvi/include/keyvi/dictionary/match.h
- keyvi/include/keyvi/dictionary/matching/fuzzy_matching.h
- keyvi/include/keyvi/index/index.h
- keyvi/include/keyvi/index/internal/base_index_reader.h
- keyvi/include/keyvi/index/internal/read_only_segment.h
- keyvi/include/keyvi/index/internal/segment.h
- keyvi/tests/keyvi/index/read_only_index_test.cpp
- python/description.md
- python/src/addons/Index.pyx
- python/src/addons/ReadOnlyIndex.pyx
- python/src/pxds/index.pxd
- python/src/pxds/read_only_index.pxd
- python/tests/index/index_test.py
- sphinx-docs/cpp/index.rst
- sphinx-docs/index.rst
- sphinx-docs/python/index.rst
implements GetFuzzy for keyvi index, utilizing the state traversers introduced in #204.
> add GetFuzzy to keyvi index

- CMakeLists.txt
- keyvi/include/keyvi/dictionary/util/endian.h
- keyvi/include/keyvi/index/internal/segment.h
- keyvi/include/keyvi/testing/index_mock.h
- keyvi/include/keyvi/testing/temp_dictionary.h
- keyvi/include/keyvi/util/os_utils.h
- keyvi/tests/keyvi/dictionary/dictionary_compiler_test.cpp
- keyvi/tests/keyvi/dictionary/dictionary_index_compiler_test.cpp
- keyvi/tests/keyvi/dictionary/dictionary_properties_test.cpp
- keyvi/tests/keyvi/dictionary/fsa/internal/json_value_store_test.cpp
fix some more issues found on windows
> More msvc related fixes

- keyvi/include/keyvi/dictionary/dictionary_compiler.h
- keyvi/include/keyvi/dictionary/dictionary_index_compiler.h
- keyvi/include/keyvi/dictionary/fsa/generator.h
- keyvi/include/keyvi/util/os_utils.h
- keyvi/include/keyvi/vector/vector_file.h
- python/src/pxds/generator.pxd
- python/tests/dictionary_compiler_test.py
- python/tests/vector/basic_test.py
assert broken stream
fixes #224
> check stream for WriteToFile

- keyvi/include/keyvi/dictionary/fsa/internal/json_value_store.h
- keyvi/tests/keyvi/dictionary/fsa/internal/json_value_store_test.cpp
a few json value store cleanups
> a few json value store cleanups

- .github/workflows/python.yml
- keyvi/include/keyvi/dictionary/fsa/automata.h
- keyvi/include/keyvi/dictionary/fsa/internal/json_value_store.h
- keyvi/include/keyvi/dictionary/fsa/internal/sparse_array_builder.h
- keyvi/include/keyvi/dictionary/fsa/internal/sparse_array_persistence.h
- keyvi/include/keyvi/dictionary/fsa/internal/unpacked_state.h
- keyvi/include/keyvi/dictionary/fsa/internal/value_store_persistence.h
- keyvi/include/keyvi/util/vint.h
- keyvi/tests/keyvi/util/vint_test.cpp
cleanup vint implementation, improve vint length performance
> cleanup vint implementation

- keyvi/include/keyvi/dictionary/dictionary.h
- keyvi/include/keyvi/dictionary/matching/fuzzy_matching.h
- keyvi/tests/keyvi/index/read_only_index_test.cpp
- python/src/pxds/dictionary.pxd
- python/tests/dictionary/get_fuzzy_test.py
fix fuzzy matching for the exact prefix case
fixes #244
> fix fuzzy matching for the exact prefix case

- .github/workflows/python.yml
- rust/Cargo.toml
- rust/src/dictionary.rs
fix build issues for rust and python on macos
> fix build issues

- .github/workflows/manylinux.yml
- .github/workflows/python.yml
- python/build_macosx_wheels.sh
> update python versions

- python/build_macosx_wheels.sh
- python/setup.py
repair build on newer M1/2/3 macs
> repair build on newer M1/2/3 macs

- .github/workflows/docs.yml
- .github/workflows/keyvi.yml
- .github/workflows/rust.yml
- .github/workflows/style.yml
update images on linux and use a more recent version of clang-format
> update ubuntu images and clang-format

- .github/workflows/python-cibuildwheel.yml
> bump actions upload following the migration guide

- .github/workflows/keyvi.yml
- .github/workflows/python-cibuildwheel.yml
workaround inconsistency problems between github runner image and brew on macos
relates: https://github.com/actions/setup-python/issues/577
> Fix workflow runners on macos

- keyvi/include/keyvi/dictionary/dictionary.h
- keyvi/include/keyvi/dictionary/matching/multiword_completion_matching.h
- keyvi/include/keyvi/testing/matching_test_utils.h
- keyvi/tests/keyvi/dictionary/matching/multiword_completion_matching_test.cpp
- keyvi/tests/keyvi/dictionary/matching/prefix_completion_matching_test.cpp
- python/setup.py
- python/src/pxds/dictionary.pxd
- python/tests/dictionary/dictionary_multiword_completion_test.py
implements multiword completion in the new style, supporting custom filters as recently added for the new prefix completions
> Re-implement multiword completions with filtering support

- keyvi/include/keyvi/index/internal/read_only_segment.h
improve how deletes are read by avoiding temporary object creation
> improve reading of deleting keys for keyvi index

- .github/workflows/python-dockerimages-cibuildwheel.yml
- docker/manylinux-builder/Dockerfile
- base image updates, e.g. python 3.14
- boost 1.88.0
- cmake 3.31.8
- ccache 4.11.3
> update versions and also trigger re-build for python 3.14

- .github/workflows/keyvi.yml
- CMakeLists.txt
remove pinning of boost@1.85, all issues shall be fixed
> remove pinning of boost brew package for mac
